# Generated by Django 5.1.1 on 2024-09-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headertext',
            name='html_class',
        ),
        migrations.RemoveField(
            model_name='headertext',
            name='url_name',
        ),
        migrations.AddField(
            model_name='headertext',
            name='html_icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='headertext',
            name='html_main',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='headertext',
            name='url_icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='headertext',
            name='url_main',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
