# Generated by Django 5.1.1 on 2024-09-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_html_icon_headertext_quastion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBegin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.TextField(blank=True, max_length=255, null=True)),
                ('description2', models.TextField(blank=True, max_length=255, null=True)),
                ('description3', models.TextField(blank=True, max_length=255, null=True)),
                ('description4', models.TextField(blank=True, max_length=255, null=True)),
                ('description5', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'About Begin',
                'verbose_name_plural': 'About Begin',
            },
        ),
        migrations.CreateModel(
            name='AboutBest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.TextField(blank=True, max_length=255, null=True)),
                ('description2', models.TextField(blank=True, max_length=255, null=True)),
                ('description3', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'About Best',
                'verbose_name_plural': 'About Best',
            },
        ),
        migrations.CreateModel(
            name='AboutSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.TextField(blank=True, max_length=255, null=True)),
                ('description2', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'About Support',
                'verbose_name_plural': 'About Support',
            },
        ),
        migrations.CreateModel(
            name='AboutTogether',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.TextField(blank=True, max_length=255, null=True)),
                ('description2', models.TextField(blank=True, max_length=255, null=True)),
                ('description3', models.TextField(blank=True, max_length=255, null=True)),
                ('description4', models.TextField(blank=True, max_length=255, null=True)),
                ('description5', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'About Together',
                'verbose_name_plural': 'About Together',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Serviceblocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='service_bloks')),
            ],
            options={
                'verbose_name': 'Serviceblocks',
                'verbose_name_plural': 'Serviceblocks',
            },
        ),
    ]
