# Generated by Django 5.1.1 on 2024-09-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_aboutbegin_aboutbest_aboutsupport_abouttogether_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headertext',
            old_name='quastion',
            new_name='question',
        ),
    ]
