# Generated by Django 5.1.1 on 2024-09-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_quastion_headertext_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblocks',
            name='image',
            field=models.ImageField(upload_to='service_blocks'),
        ),
    ]
