# Generated by Django 5.1.1 on 2024-09-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_serviceblocks_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceblocks',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
