# Generated by Django 5.1.1 on 2024-09-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_serviceblocks_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='evants_blocks')),
            ],
            options={
                'verbose_name': 'Events Blocks',
                'verbose_name_plural': 'Events Blocks',
            },
        ),
        migrations.CreateModel(
            name='FactsBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Facts Blocks',
                'verbose_name_plural': 'Facts Blocks',
            },
        ),
        migrations.CreateModel(
            name='LatestCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Latest Courses',
                'verbose_name_plural': 'Latest Courses',
            },
        ),
    ]
