# Generated by Django 5.1.1 on 2024-09-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_eventsblocks_factsblocks_latestcourses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsblocks',
            old_name='tag',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='eventsblocks',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventsblocks',
            name='title',
        ),
        migrations.AddField(
            model_name='eventsblocks',
            name='title1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventsblocks',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
