# Generated by Django 5.1.1 on 2024-09-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_tag_eventsblocks_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestcourses',
            name='categore1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='latestcourses',
            name='categore2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='latestcourses',
            name='categore3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
