# Generated by Django 5.1.1 on 2024-09-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_categore1_latestcourses_category1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='authors')),
            ],
            options={
                'verbose_name': 'Authors',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('offer_percent', models.CharField(blank=True, max_length=50, null=True)),
                ('html_class', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='events')),
                ('data', models.CharField(blank=True, help_text='FontAwesome icon', max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('html_class', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'Events',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='team_members')),
                ('social_title', models.CharField(blank=True, max_length=50, null=True)),
                ('social_url', models.URLField(blank=True, max_length=255)),
                ('social_html_class', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Team Members',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Upcoming Events',
                'verbose_name_plural': 'Upcoming Events',
            },
        ),
        migrations.AlterField(
            model_name='eventsblocks',
            name='image',
            field=models.ImageField(upload_to='events_blocks'),
        ),
    ]
