# Generated by Django 5.1.1 on 2024-09-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_authors_contactus_events_teammembers_testimonial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('html_class', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
            },
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='social_html_class',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='social_title',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='social_url',
        ),
    ]
