# Generated by Django 5.1.1 on 2024-09-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_socials_remove_teammembers_social_html_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='valide',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
